name: Build + Tests
env:
  cli-id: anchor-v0.22.dev-7b86aed-solana-1.10.5
  SWAP_PROGRAM_OWNER_FEE_ADDRESS: HfoTxFR1Tm6kGmWgYWD6J7YHVy1UwqSULUGVLXkJqaKN
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build-cli-deps:
    runs-on: ubuntu-latest
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor

      - id: install-os-deps
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - id: install-rust-toolchain
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - id: install-solana-tools
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.10.5/install)"

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV

      - id: install-anchor-cli
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/project-serum/anchor --tag v0.22.0 anchor-cli --locked

  build:
    runs-on: ubuntu-latest
    needs: [build-cli-deps]
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - run: npm install -g typescript
      - run: npm install -g yarn
      - run: npm install -g ts-mocha
      - run: npm install -g @project-serum/anchor
      - run: yarn
      - run: solana-keygen new --no-bip39-passphrase
      - run: cargo test
      - run: yarn run build
      - run: anchor test
      - run: cargo fmt -- --check
      - run: yarn run prettier --c ./

  audit:
    runs-on: ubuntu-latest
    needs: [build-cli-deps]
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Check-out the repository
        uses: actions/checkout@v2

      - name: Soteria Audit
        continue-on-error: false          # set to true if you don't want to fail jobs
        uses: silas-x/soteria-action@main
        with:                             # remove if not passing arguments below
          solana-version: "1.10.5"        # not required
          run-mode: "-analyzeAll"         # not required
          cargo-com: "."                  # not required
          program-path: "programs/dca-vault"               # not required

    # - name: Install Soteria
    #   run: | 
    #     echo Installing Soteria... ðŸ”¬
    #     sh -c "$(curl -k https://supercompiler.xyz/install)"
    #     export PATH=$PWD/soteria-linux-develop/bin/:$PATH
    #     echo "$PWD/soteria-linux-develop/bin" >> $GITHUB_PATH
    #   shell: bash
    # - name: Run Soteria
    #   run: |
    #     echo Running Soteria... ðŸš€
    #     cd programs
    #     soteria -analyzeAll .
    #   shell: bash
